version: "2.1"
services:
    minio:
        image: minio/minio
        command: server /data
        ports:
            - 9000:9000
        environment:
            - MINIO_ACCESS_KEY=A8eENTqgEE7uYL7R
            - MINIO_SECRET_KEY=82bmVoDRkZgwy4B3PXkLzpXiuqGVZMug
    postgres:
        image: postgres:alpine
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_HOST_AUTH_METHOD=trust
        ports:
            - 5432:5432
        volumes:
            - postgres:/var/lib/postgresql/data


volumes:
    postgres:
