<Project Sdk="Microsoft.NET.Sdk.Razor">

  <ItemGroup>
    <ProjectReference Include="..\Sitko.Blockly\Sitko.Blockly.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="8.0.12" />
    <PackageReference Include="Sitko.Core.Blazor" Version="11.49.0" />
    <PackageReference Include="Sitko.Core.Blazor.FileUpload" Version="11.49.0" />
  </ItemGroup>

</Project>
