<Project Sdk="Microsoft.NET.Sdk.Razor">

  <ItemGroup>
    <ProjectReference Include="..\Sitko.Blockly\Sitko.Blockly.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web"/>
    <PackageReference Include="Sitko.Core.Blazor"/>
    <PackageReference Include="Sitko.Core.Blazor.FileUpload"/>
    <PackageReference Include="Sitko.Blazor.ScriptInjector"/>
  </ItemGroup>

</Project>
