name: CI

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build:
        runs-on: ubuntu-latest
        container: ghcr.io/sitkoru/actions-container
        env:
            PROJECT: Sitko.Blockly
            ANTDESIGN_PROJECT: Sitko.Blockly.AntDesign
            EF_PROJECT: Sitko.Blockly.EntityFrameworkCore
            TEST_PROJECT: Sitko.Blockly.Tests
        steps:
            -   name: Checkout code
                uses: actions/checkout@v2.3.4
            -   name: Install node.js
                uses: actions/setup-node@v2.1.5
                with:
                    node-version: '15'
            -   name: Install .NET Core 3.1
                uses: actions/setup-dotnet@v1.8.0
                with:
                    dotnet-version: '3.1.x'
            -   name: Install .NET 5.0
                uses: actions/setup-dotnet@v1.8.0
                with:
                    dotnet-version: '5.0.x'
            -   name: Build antdesign js
                working-directory: src/${{ env.ANTDESIGN_PROJECT }}/Web
                shell: bash
                run: |
                    npm ci
                    npm run prod
            -   name: Create main package
                run: dotnet pack -c Release src/${{ env.PROJECT }}
            -   name: Create antdesign package
                run: dotnet pack -c Release src/${{ env.ANTDESIGN_PROJECT }}
            -   name: Create ef package
                run: dotnet pack -c Release src/${{ env.EF_PROJECT }}
            -   name: Add Github Actions logger
                run: dotnet add tests/${{ env.TESTS_PROJECT }}/${{ env.TESTS_PROJECT }}.csproj package GitHubActionsTestLogger
            -   name: Run tests
                run: dotnet test --logger GitHubActions tests/${{ env.TESTS_PROJECT }}/${{ env.TESTS_PROJECT }}.csproj
