name: Release

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/sitkoru/actions-container
    env:
      PROJECT: Sitko.Blockly
      BLAZOR_PROJECT: Sitko.Blockly.Blazor
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Prepare
        id: prep
        shell: bash
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo ::set-output name=version::${VERSION}
      - name: Install node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: |
            src/Sitko.Blockly.Blazor/Web/package.json
      - name: Build blazor js
        working-directory: src/${{ env.BLAZOR_PROJECT }}/Web
        shell: bash
        run: |
          npm ci
          npm run prod
      - name: Publish main library
        uses: sitkoru/nuget-release-action@v1
        with:
          version: ${{ steps.prep.outputs.version }}
          project_path: src/Sitko.Blockly/Sitko.Blockly.csproj
          nuget_host: https://api.nuget.org/v3/index.json
          nuget_token: ${{ secrets.NUGET_API_KEY }}
      - name: Publish Blazor library
        uses: sitkoru/nuget-release-action@v1
        with:
          version: ${{ steps.prep.outputs.version }}
          project_path: src/Sitko.Blockly.Blazor/Sitko.Blockly.Blazor.csproj
          nuget_host: https://api.nuget.org/v3/index.json
          nuget_token: ${{ secrets.NUGET_API_KEY }}
      - name: Publish AntDesign library
        uses: sitkoru/nuget-release-action@v1
        with:
          version: ${{ steps.prep.outputs.version }}
          project_path: src/Sitko.Blockly.AntDesign/Sitko.Blockly.AntDesign.csproj
          nuget_host: https://api.nuget.org/v3/index.json
          nuget_token: ${{ secrets.NUGET_API_KEY }}
      - name: Publish MudBlazor library
        uses: sitkoru/nuget-release-action@v1
        with:
          version: ${{ steps.prep.outputs.version }}
          project_path: src/Sitko.Blockly.MudBlazor/Sitko.Blockly.MudBlazor.csproj
          nuget_host: https://api.nuget.org/v3/index.json
          nuget_token: ${{ secrets.NUGET_API_KEY }}
      - name: Publish EF library
        uses: sitkoru/nuget-release-action@v1
        with:
          version: ${{ steps.prep.outputs.version }}
          project_path: src/Sitko.Blockly.EntityFrameworkCore/Sitko.Blockly.EntityFrameworkCore.csproj
          nuget_host: https://api.nuget.org/v3/index.json
          nuget_token: ${{ secrets.NUGET_API_KEY }}
      - name: Publish HtmlParser library
        uses: sitkoru/nuget-release-action@v1
        with:
          version: ${{ steps.prep.outputs.version }}
          project_path: src/Sitko.Blockly.HtmlParser/Sitko.Blockly.HtmlParser.csproj
          nuget_host: https://api.nuget.org/v3/index.json
          nuget_token: ${{ secrets.NUGET_API_KEY }}

